### ISSUE TITLE
Port opensnitch-tui to build with rustc 0.85?

### ISSUE THREAD

**Issue by petterreinholdtsen** [amalbansode/opensnitch-tui#5]
I tried building opensnitch-tui on Debian Stable, but ran into these compiler errors:

```
   Compiling opensnitch-tui v0.0.4 (/home/pere/src/opensnitch-tui-upstream)
error[E0658]: `let` expressions in this position are unstable
   --> src/app.rs:439:12
    |
439 |         if let Some(conn) = &self.tui_state.current_connection
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
  --> src/operator_util.rs:99:16
   |
99 |             && let Some(user_id) = self.user_id
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> src/operator_util.rs:104:16
    |
104 |             && let Some(ppath) = &self.ppath
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> src/operator_util.rs:109:16
    |
109 |             && let Some(dst_ip) = &self.dst_ip
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> src/operator_util.rs:114:16
    |
114 |             && let Some(dst_port) = self.dst_port
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> src/operator_util.rs:119:16
    |
119 |             && let Some(protocol) = &self.protocol
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
  --> src/ui.rs:72:12
   |
72 |         if let Some(conn) = &self.current_connection
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
  --> src/ui.rs:73:16
   |
73 |             && let Ok(remaining_time) = conn.expiry_ts.duration_since(now)
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `opensnitch-tui` (bin "opensnitch-tui") due to 8 previous errors
```

It would be great if the code could be ported to rust 1.85.0 instead of having to use 1.88+ as instructed by [the github issue](https://github.com/rust-lang/rust/issues/53667)

**Comment by amalbansode** [comment]
Thanks for the report. Let me know if 33e8b4f00ada9f3ae55a1c67ba2b3bdeda0a8f7e fixes this?

**Comment by petterreinholdtsen** [comment]
[Amal Bansode]
> Thanks for the report. Let me know if
> 33e8b4f00ada9f3ae55a1c67ba2b3bdeda0a8f7e fixes this?

The latest edition in 33e8b4f00ada9f3ae55a1c67ba2b3bdeda0a8f7e built
just fine:

   Compiling opensnitch-tui v0.0.4 (/home/pere/src/opensnitch-tui-upstream)
    Finished `release` profile [optimized] target(s) in 37.75s

-- 
Happy hacking
Petter Reinhodltsen
